on:
  push:
    branches: [main, master]
    paths-ignore: '**/README.md'
  pull_request:
    branches: [main, master]
    paths-ignore: '**/README.md'

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup system dependencies
        run: |
          packages=(
            libcurl4-openssl-dev
            libgdal-dev
            libproj-dev
            libudunits2-dev
          )
          sudo apt-get update
          sudo apt-get install --yes "${packages[@]}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup R dependencies
        uses: r-lib/actions/setup-renv@v2
   
      - name: Push to shinyapps.io
        if: github.event_name == 'push'
        run: |
          install.packages("rsconnect", repos="http://cran.us.r-project.org")
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACC_NAME}}", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")
          rsconnect::deployApp(appName = 'ZooShopInsights', forceUpdate = TRUE)
        shell: Rscript {0}
